services:
  inkraft:
    build: .
    container_name: inkraft
    ports:
      - "8000:8000"
    environment:
      - DEVICE=cuda
    volumes:
      - ./outputs:/app/outputs
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
